language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJ7SXC23CS2USONIA
  secret_access_key:
    secure: sl7PtcRvlDvrEojGqt2nISTVfjp9xYyCnNPuWqm9O6BjMJ5Eu0FzBYthfcU12pKE/Gq7a4NDv45gJRHVJhBGm+AWIUWQXW81nwb2PlxN/rrooYIdDhyeazyVP29sd0omn9GbdnTwvnYEixiohzZqoVbf9sz2EAnftWA8i2Cxb3w=
  bucket: biojs
  upload-dir: parser/latest
  acl: public-read
  detect_encoding: true # allow compressed uploads
  skip_cleanup: true
  local-dir: build
  on:
      repo: biojs/biojs-meta-parser
